# ===== Matrix Authentication =====
# The Matrix homeserver to connect to
homeserver: https://matrix.example.com
# The Matrix username of the MSC Link bot
username: "@mscbot:example.com"
# A file containing the Matrix user password
password_file: /path/to/password/file

# Automatically join the bot to any room that it is invited to
auto_join: false

# ===== Database Settings =====
database:
  # The database type. Only "sqlite3" is supported
  type: sqlite3
  # The database URI.
  #   SQLite: A raw file path is supported, but `file:<path>?_txlock=immediate` is recommended.
  #           https://github.com/mattn/go-sqlite3#connection-string
  uri: crypto.db
  # Maximum number of connections. Mostly relevant for Postgres.
  max_open_conns: 20
  max_idle_conns: 2
  # Maximum connection idle time and lifetime before they're closed. Disabled if null.
  # Parsed with https://pkg.go.dev/time#ParseDuration
  max_conn_idle_time: null
  max_conn_lifetime: null

# ===== Logger Settings =====
# See https://github.com/tulir/zeroconfig for details.
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      format: json
      filename: ./logs/chatwoot-bot.log
      max_size: 100
      max_backups: 10
      compress: true

